variables:
  BuildConfiguration: Release

trigger:
- develop

pr:
- develop

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build SDK Library Targeting NetStandard2.0'
  inputs:
    command: 'build'
    configuration: '$(BuildConfiguration)'
    projects: src/mtconnect_adapter_sdk.csproj
- task: DotNetCoreCLI@2
  displayName: 'Build Test Projects Targeting DotNetCore 2.2'
  inputs:
    command: 'build'
    configuration: '$(BuildConfiguration)'
    projects: test/mtconnect_adapter_sdk.utests.csproj
- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '**/*.utests.csproj'
- task: DotNetCoreCLI@2
  displayName: 'Generate NuGet Package'
  inputs:
    command: pack
    packagesToPack: './src/mtconnect_adapter_sdk.csproj'
    arguments: --version-suffix 'prerelease_$(Build.BuildId)'
    includesymbols: true
    includesource: true
    outputDir: '$(Build.ArtifactStagingDirectory)'
    verbosityPack: detailed
- task: DotNetCoreCLI@2
  displayName: 'Publish NuGet Package to mtconnect_sdk_feed'
  inputs:
    command: 'push'
    feedPublish: 'mtconnect_sdk_feed'