variables: 
  BuildConfiguration: 'Release'
  BuildPlatform: AnyCPU
  VersionNumberConfigurationFile: 'GitVersion.yml'
  ProjectsToBuild: '**/*.csproj'
  ProjectsToPack: 'src/**/*.csproj'
  ProjectsToTest: '**/*.tests.csproj'

pool:
  vmImage: 'vs2015-win2012r2'

steps: 
- bash: |
    echo '----------- Build Agent Information -----------'
    echo 'OS: $(Agent.OS)'
    echo 'Build Directory: $(Agent.BuildDirectory)'
    echo 'Home Directory: $(Agent.HomeDirectory)'
    echo '------------ Trigger Information --------------'
    echo 'Build Reason: $(Build.Reason)'
    echo 'Source Branch Name: $(Build.SourceBranch)'
    echo 'Commit Hash: $(Build.SourceVersion)'
    echo '------------- Build Information ---------------'
    echo 'Artifact staging directory: $(Build.ArtifactStagingDirectory)'
    echo '-----------------------------------------------'
  displayName: 'Log Variables of Interest'
- task: gittools.gitversion.gitversion-task.GitVersion@5
  displayName: 'Update build/release version using GitVersion'
  inputs:
    useConfigFile: true
    configFilePath: GitVersion.yml
- task: UseDotNet@2
  displayName: 'Install .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1.x
    installationPath: $(Agent.ToolsDirectory)/dotnet
- task: DotNetCoreCLI@2
  displayName: 'Build Library and UnitTests'
  inputs:
    command: 'build'
    projects: |
      ./src/mtconnect_adapter_sdk.csproj
      ./test/mtconnect_adapter_sdk.utests.csproj
    arguments: --configuration $(BuildConfiguration) --version-suffix $(Build.BuildId) --verbosity diag
- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: 'test/**/*.utests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Package Library as NuPkg' 
  inputs: 
    command: pack
    packagesToPack: '$(ProjectsToPack)' 
    nobuild: true 
    versioningScheme: byEnvVar 
    versionEnvVar: GitVersion.NuGetVersion

- task: DotNetCoreCLI@2 
  displayName: 'Publish NuGet Package' 
  inputs: 
    command: push
    feedPublish: 'mtconnect_sdk_feed'
    versioningScheme: byBuildNumber