variables:
  BuildConfiguration: Release

trigger:
- develop

pr:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build Library and Test Projects'
  inputs:
    command: 'build'
    configuration: '$(BuildConfiguration)'
    projects: |
      src/mtconnect_adapter_sdk.csproj
      test/mtconnect_adapter_sdk.utests.csproj
- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
- task: DotNetCoreCLI@2
  displayName: 'Generate NuGet Package'
  inputs:
    command: pack
    packagesToPack: './src/mtconnect_adapter_sdk.csproj'
    includesymbols: true
    outputDir: '$(Build.ArtifactStagingDirectory)'
- task: DotNetCoreCLI@2
  displayName: 'Publish NuGet Package to mtconnect_sdk_feed'
  inputs:
    command: 'push'
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    feedPublish: 'mtconnect_sdk_feed'