variables:
  BuildConfiguration: Release

trigger:
- develop

pr:
- develop

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    configuration: '$(BuildConfiguration)'
    arguments: --version-suffix $(Build.BuildId)
- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '**/*.utests.csproj'
- task: DotNetCoreCLI@2
  displayName: 'Generate NuGet Package'
  inputs:
    command: custom
    custom: pack
    projects: ./src/mtconnect_adapter_sdk.csproj
    arguments: '--configuration $(BuildConfiguration) --version-suffix prerelease-$(Build.BuildId) --include-source'
- task: DotNetCoreCLI@2
  displayName: 'Publish NuGet Package to mtconnect_sdk_feed'
  inputs:
    command: 'push'
    feedPublish: 'mtconnect_sdk_feed'